name: webrailnavoverlay
description: A Flutter package for a web-based navigation rail with overlay support.
version: 0.0.1
homepage: https://github.com/princetomar27/flutterwebrailnavoverlay
publish_to: 'https://pub.dev'

environment:
  sdk: '>=2.12.0'  # Allows Dart SDK versions from 2.12.0 and up

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: WebRailNavOverlayPlugin
