name: webrailnavoverlay
description: A Flutter package for a web-based navigation rail with overlay support.
version: 0.0.3
homepage: https://github.com/princetomar27/flutterwebrailnavoverlay

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

fileName: src/webrailnavoverlay.dart

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: WebRailNavOverlayPlugin
        fileName: webrailnavoverlay.dart 
